[book]
authors = ["Max <mxcop>"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "../docs"

[output.html]
theme = "theme"
default-theme = "dark"
preferred-dark-theme = "earthsong"
additional-css = ["theme/css/alerts.css"]

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[preprocessor.syntect]
custom-theme = "assets/earthsong.tmTheme"
